"""Audition hired to false

Revision ID: a023c53a7ee5
Revises: 472a54fdf789
Create Date: 2025-03-09 15:44:41.771583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a023c53a7ee5'
down_revision = '472a54fdf789'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
